# 界面绘制,无需修改
from PyQt5 import QtCore, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(548, 415)
        MainWindow.setMinimumSize(QtCore.QSize(509, 399))
        MainWindow.setMaximumSize(QtCore.QSize(548, 439))
        MainWindow.setWindowOpacity(0.95)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainBox = QtWidgets.QGroupBox(self.centralwidget)
        self.mainBox.setGeometry(QtCore.QRect(10, 10, 531, 401))
        self.mainBox.setMinimumSize(QtCore.QSize(531, 401))
        self.mainBox.setMaximumSize(QtCore.QSize(531, 401))
        self.mainBox.setAlignment(QtCore.Qt.AlignCenter)
        self.mainBox.setCheckable(False)
        self.mainBox.setObjectName("mainBox")
        self.edgeBox = QtWidgets.QGroupBox(self.mainBox)
        self.edgeBox.setGeometry(QtCore.QRect(200, 20, 131, 171))
        self.edgeBox.setMinimumSize(QtCore.QSize(131, 171))
        self.edgeBox.setMaximumSize(QtCore.QSize(131, 171))
        self.edgeBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.edgeBox.setObjectName("edgeBox")
        self.cannyButton = QtWidgets.QRadioButton(self.edgeBox)
        self.cannyButton.setGeometry(QtCore.QRect(20, 20, 89, 16))
        self.cannyButton.setMinimumSize(QtCore.QSize(89, 16))
        self.cannyButton.setMaximumSize(QtCore.QSize(89, 16))
        self.cannyButton.setChecked(True)
        self.cannyButton.setObjectName("cannyButton")
        self.sobelButton = QtWidgets.QRadioButton(self.edgeBox)
        self.sobelButton.setGeometry(QtCore.QRect(20, 50, 89, 16))
        self.sobelButton.setMinimumSize(QtCore.QSize(89, 16))
        self.sobelButton.setMaximumSize(QtCore.QSize(89, 16))
        self.sobelButton.setChecked(False)
        self.sobelButton.setObjectName("sobelButton")
        self.robertsButton = QtWidgets.QRadioButton(self.edgeBox)
        self.robertsButton.setGeometry(QtCore.QRect(20, 80, 89, 16))
        self.robertsButton.setMinimumSize(QtCore.QSize(89, 16))
        self.robertsButton.setMaximumSize(QtCore.QSize(89, 16))
        self.robertsButton.setObjectName("robertsButton")
        self.prewittButton = QtWidgets.QRadioButton(self.edgeBox)
        self.prewittButton.setGeometry(QtCore.QRect(20, 110, 89, 16))
        self.prewittButton.setMinimumSize(QtCore.QSize(89, 16))
        self.prewittButton.setMaximumSize(QtCore.QSize(89, 16))
        self.prewittButton.setObjectName("prewittButton")
        self.logButton = QtWidgets.QRadioButton(self.edgeBox)
        self.logButton.setGeometry(QtCore.QRect(20, 140, 89, 16))
        self.logButton.setMinimumSize(QtCore.QSize(89, 16))
        self.logButton.setMaximumSize(QtCore.QSize(89, 16))
        self.logButton.setObjectName("logButton")
        self.histogramButton = QtWidgets.QPushButton(self.mainBox)
        self.histogramButton.setGeometry(QtCore.QRect(220, 200, 91, 23))
        self.histogramButton.setMinimumSize(QtCore.QSize(91, 23))
        self.histogramButton.setMaximumSize(QtCore.QSize(91, 23))
        self.histogramButton.setObjectName("histogramButton")
        self.loadpicButton = QtWidgets.QPushButton(self.mainBox)
        self.loadpicButton.setGeometry(QtCore.QRect(330, 260, 75, 23))
        self.loadpicButton.setMinimumSize(QtCore.QSize(75, 23))
        self.loadpicButton.setMaximumSize(QtCore.QSize(75, 23))
        self.loadpicButton.setObjectName("loadpicButton")
        self.defoggingButton = QtWidgets.QPushButton(self.mainBox)
        self.defoggingButton.setGeometry(QtCore.QRect(440, 260, 75, 23))
        self.defoggingButton.setMinimumSize(QtCore.QSize(75, 23))
        self.defoggingButton.setMaximumSize(QtCore.QSize(75, 23))
        self.defoggingButton.setObjectName("defoggingButton")
        self.defoggingBox = QtWidgets.QGroupBox(self.mainBox)
        self.defoggingBox.setGeometry(QtCore.QRect(10, 230, 301, 161))
        self.defoggingBox.setMinimumSize(QtCore.QSize(301, 161))
        self.defoggingBox.setMaximumSize(QtCore.QSize(301, 161))
        self.defoggingBox.setObjectName("defoggingBox")
        self.horizontalSlider_1 = QtWidgets.QSlider(self.defoggingBox)
        self.horizontalSlider_1.setGeometry(QtCore.QRect(10, 20, 111, 16))
        self.horizontalSlider_1.setMinimumSize(QtCore.QSize(111, 16))
        self.horizontalSlider_1.setMaximumSize(QtCore.QSize(111, 16))
        self.horizontalSlider_1.setMinimum(0)
        self.horizontalSlider_1.setMaximum(256)
        self.horizontalSlider_1.setProperty("value", 50)
        self.horizontalSlider_1.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_1.setObjectName("horizontalSlider_1")
        self.horizontalSlider_2 = QtWidgets.QSlider(self.defoggingBox)
        self.horizontalSlider_2.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.horizontalSlider_2.setMinimumSize(QtCore.QSize(111, 16))
        self.horizontalSlider_2.setMaximumSize(QtCore.QSize(111, 16))
        self.horizontalSlider_2.setMaximum(320)
        self.horizontalSlider_2.setProperty("value", 75)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.horizontalSlider_3 = QtWidgets.QSlider(self.defoggingBox)
        self.horizontalSlider_3.setGeometry(QtCore.QRect(10, 100, 111, 16))
        self.horizontalSlider_3.setMinimumSize(QtCore.QSize(111, 16))
        self.horizontalSlider_3.setMaximumSize(QtCore.QSize(111, 16))
        self.horizontalSlider_3.setMaximum(100)
        self.horizontalSlider_3.setPageStep(10)
        self.horizontalSlider_3.setProperty("value", 95)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.horizontalSlider_4 = QtWidgets.QSlider(self.defoggingBox)
        self.horizontalSlider_4.setGeometry(QtCore.QRect(10, 140, 111, 16))
        self.horizontalSlider_4.setMinimumSize(QtCore.QSize(111, 16))
        self.horizontalSlider_4.setMaximumSize(QtCore.QSize(111, 16))
        self.horizontalSlider_4.setMaximum(250)
        self.horizontalSlider_4.setProperty("value", 200)
        self.horizontalSlider_4.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_4.setObjectName("horizontalSlider_4")
        self.label_1 = QtWidgets.QLabel(self.defoggingBox)
        self.label_1.setGeometry(QtCore.QRect(120, 20, 101, 21))
        self.label_1.setMinimumSize(QtCore.QSize(101, 21))
        self.label_1.setMaximumSize(QtCore.QSize(101, 21))
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.defoggingBox)
        self.label_2.setGeometry(QtCore.QRect(120, 60, 101, 21))
        self.label_2.setMinimumSize(QtCore.QSize(101, 21))
        self.label_2.setMaximumSize(QtCore.QSize(101, 21))
        self.label_2.setScaledContents(False)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.defoggingBox)
        self.label_3.setGeometry(QtCore.QRect(130, 100, 81, 21))
        self.label_3.setMinimumSize(QtCore.QSize(81, 21))
        self.label_3.setMaximumSize(QtCore.QSize(81, 21))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.defoggingBox)
        self.label_4.setGeometry(QtCore.QRect(130, 140, 81, 21))
        self.label_4.setMinimumSize(QtCore.QSize(81, 21))
        self.label_4.setMaximumSize(QtCore.QSize(81, 21))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.lineEdit_1 = QtWidgets.QLineEdit(self.defoggingBox)
        self.lineEdit_1.setGeometry(QtCore.QRect(220, 20, 71, 20))
        self.lineEdit_1.setMinimumSize(QtCore.QSize(61, 20))
        self.lineEdit_1.setMaximumSize(QtCore.QSize(71, 20))
        self.lineEdit_1.setText("")
        self.lineEdit_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_1.setClearButtonEnabled(False)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.defoggingBox)
        self.lineEdit_2.setGeometry(QtCore.QRect(220, 60, 71, 20))
        self.lineEdit_2.setMinimumSize(QtCore.QSize(61, 20))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(71, 20))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.defoggingBox)
        self.lineEdit_3.setGeometry(QtCore.QRect(220, 100, 71, 20))
        self.lineEdit_3.setMinimumSize(QtCore.QSize(61, 20))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(71, 20))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.defoggingBox)
        self.lineEdit_4.setGeometry(QtCore.QRect(220, 140, 71, 20))
        self.lineEdit_4.setMinimumSize(QtCore.QSize(61, 20))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(71, 20))
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.savepicButton = QtWidgets.QPushButton(self.mainBox)
        self.savepicButton.setGeometry(QtCore.QRect(440, 310, 75, 23))
        self.savepicButton.setMinimumSize(QtCore.QSize(75, 23))
        self.savepicButton.setMaximumSize(QtCore.QSize(75, 23))
        self.savepicButton.setObjectName("savepicButton")
        self.exitButton = QtWidgets.QPushButton(self.mainBox)
        self.exitButton.setGeometry(QtCore.QRect(380, 360, 81, 23))
        self.exitButton.setMinimumSize(QtCore.QSize(81, 23))
        self.exitButton.setMaximumSize(QtCore.QSize(81, 23))
        self.exitButton.setObjectName("exitButton")
        self.originalView = QtWidgets.QLabel(self.mainBox)
        self.originalView.setGeometry(QtCore.QRect(10, 20, 171, 171))
        self.originalView.setMinimumSize(QtCore.QSize(171, 171))
        self.originalView.setMaximumSize(QtCore.QSize(171, 171))
        self.originalView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.originalView.setText("")
        self.originalView.setWordWrap(False)
        self.originalView.setObjectName("originalView")
        self.handledView = QtWidgets.QLabel(self.mainBox)
        self.handledView.setGeometry(QtCore.QRect(350, 20, 171, 171))
        self.handledView.setMinimumSize(QtCore.QSize(171, 171))
        self.handledView.setMaximumSize(QtCore.QSize(171, 171))
        self.handledView.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.handledView.setFrameShadow(QtWidgets.QFrame.Plain)
        self.handledView.setText("")
        self.handledView.setObjectName("handledView")
        self.autoCheck = QtWidgets.QCheckBox(self.mainBox)
        self.autoCheck.setGeometry(QtCore.QRect(430, 220, 91, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoCheck.sizePolicy().hasHeightForWidth())
        self.autoCheck.setSizePolicy(sizePolicy)
        self.autoCheck.setMinimumSize(QtCore.QSize(91, 20))
        self.autoCheck.setMaximumSize(QtCore.QSize(91, 20))
        self.autoCheck.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.autoCheck.setCheckable(True)
        self.autoCheck.setChecked(False)
        self.autoCheck.setTristate(False)
        self.autoCheck.setObjectName("autoCheck")
        self.multiCheck = QtWidgets.QCheckBox(self.mainBox)
        self.multiCheck.setGeometry(QtCore.QRect(320, 220, 91, 20))
        self.multiCheck.setMinimumSize(QtCore.QSize(91, 20))
        self.multiCheck.setMaximumSize(QtCore.QSize(91, 20))
        self.multiCheck.setObjectName("multiCheck")
        self.denoiseButton = QtWidgets.QPushButton(self.mainBox)
        self.denoiseButton.setGeometry(QtCore.QRect(330, 310, 75, 23))
        self.denoiseButton.setMinimumSize(QtCore.QSize(75, 23))
        self.denoiseButton.setMaximumSize(QtCore.QSize(75, 23))
        self.denoiseButton.setObjectName("denoiseButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DIPGUI"))
        self.mainBox.setTitle(_translate("MainWindow", "数字图形处理界面"))
        self.edgeBox.setTitle(_translate("MainWindow", "边缘检测"))
        self.cannyButton.setText(_translate("MainWindow", "Canny算子"))
        self.sobelButton.setText(_translate("MainWindow", "Sobel算子"))
        self.robertsButton.setText(_translate("MainWindow", "Roberts算子"))
        self.prewittButton.setText(_translate("MainWindow", "Prewitt算子"))
        self.logButton.setText(_translate("MainWindow", "Log算子"))
        self.histogramButton.setText(_translate("MainWindow", "显示直方图"))
        self.loadpicButton.setText(_translate("MainWindow", "读取图片"))
        self.defoggingButton.setText(_translate("MainWindow", "去雾"))
        self.defoggingBox.setTitle(_translate("MainWindow", "去雾参数调节"))
        self.label_1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">滑动窗口大小</p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "导向滤波半径"))
        self.label_3.setText(_translate("MainWindow", "去雾程度"))
        self.label_4.setText(_translate("MainWindow", "大气光值"))
        self.savepicButton.setText(_translate("MainWindow", "存储图片"))
        self.exitButton.setText(_translate("MainWindow", "退出"))
        self.autoCheck.setText(_translate("MainWindow", "自动大气光值"))
        self.multiCheck.setText(_translate("MainWindow", "多尺度透射率"))
        self.denoiseButton.setText(_translate("MainWindow", "图片降噪"))
